author: H31IX
database: false
description: Travelpad plugin for Bukkit.
main: net.h31ix.travelpad.Travelpad
name: TravelPad
startup: postworld
url: http://H31IX.NET/
version: '1.8.5'
softdepend: [Vault]
commands:
  travelpad:
    description: Use travelpad
    usage: /travelpad
    aliases: t